services:
  - type: web
    name: instagram-telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: INSTA_USER
        sync: false
      - key: INSTA_PASS
        sync: false
      - key: MAX_FILESIZE_MB
        value: "50"
    autoDeploy: true
